version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./visualizations:/app/visualizations
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

# To run:
# docker-compose up -d
#
# To stop:
# docker-compose down
#
# To view logs:
# docker-compose logs -f
#
# To rebuild:
# docker-compose up -d --build